# Generated by Django 4.2.3 on 2023-08-05 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0003_alter_team_members_alter_team_task_created"),
        ("tasks", "0004_task_completed_alter_task_team_managing_it_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="assigned_task",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.task",
                verbose_name="Taches assignés",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_tasks",
            field=models.ManyToManyField(
                blank=True,
                related_name="task_created_by_user",
                to="tasks.task",
                verbose_name="taches taches créées par le user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_team",
            field=models.ManyToManyField(
                blank=True,
                related_name="teams_created_by_user",
                to="teams.team",
                verbose_name="Equipes créées par ce user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="joined_team",
            field=models.ManyToManyField(
                blank=True,
                related_name="teams_user_joined",
                to="teams.team",
                verbose_name="Equipes joins",
            ),
        ),
    ]
