# Generated by Django 4.2.3 on 2023-08-05 20:32

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("teams", "0002_initial"),
        ("tasks", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="task",
            name="team_managing_it",
            field=models.OneToOneField(
                blank=True, on_delete=django.db.models.deletion.CASCADE, to="teams.team"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="user_assigned",
            field=models.OneToOneField(
                default=users.models.User,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
            ),
        ),
    ]
