# Generated by Django 4.2.3 on 2023-08-05 22:28

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_assigned_task_alter_user_created_tasks_and_more"),
        ("tasks", "0004_task_completed_alter_task_team_managing_it_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_creator",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="task",
            name="user_assigned",
            field=models.OneToOneField(
                default=users.models.User,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_task_assigned",
                to="users.user",
            ),
        ),
    ]
