# Generated by Django 4.2.3 on 2023-08-06 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0005_alter_task_creator_alter_task_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="user_assigned",
            field=models.OneToOneField(
                default=users.models.User,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_task_assigned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
