# Generated by Django 4.2.3 on 2023-08-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        ("tasks", "0003_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(to="users.user"),
        ),
        migrations.AddField(
            model_name="team",
            name="task_created",
            field=models.ManyToManyField(to="tasks.task"),
        ),
    ]
