# Generated by Django 4.2.3 on 2023-08-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        ("tasks", "0004_task_completed_alter_task_team_managing_it_and_more"),
        ("teams", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(blank=True, to="users.user"),
        ),
        migrations.AlterField(
            model_name="team",
            name="task_created",
            field=models.ManyToManyField(blank=True, to="tasks.task"),
        ),
    ]
