# Generated by Django 4.2.3 on 2023-08-05 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_assigned_task_alter_user_created_tasks_and_more"),
        ("teams", "0003_alter_team_members_alter_team_task_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_of_the_team",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="members_of_this_team", to="users.user"
            ),
        ),
    ]
