# Generated by Django 4.2.3 on 2023-08-06 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0004_alter_team_creator_alter_team_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creator_of_the_team",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
