# Generated by Django 4.2.3 on 2023-08-06 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0005_alter_team_creator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"verbose_name": "team", "verbose_name_plural": "teams"},
        ),
    ]
